app/profiles/forms.py
import flask_wtf
from wtforms import (StringField, SubmitField, SelectField, IntegerField, 
        TextAreaField)
from wtforms.validators import Length, DataRequired, Email
from wtforms.fields.html5 import DateField

class Add_Order_Form(flask_wtf.FlaskForm):
    order_id = SelectField('select order', validators = [DataRequired()])
    submit = SubmitField('add order')


class Service_Form(flask_wtf.FlaskForm):
    vehicle_id = SelectField('select vehicle', validators = [DataRequired()])
    description = TextAreaField('service description',
            validators = [DataRequired()])
    cost = IntegerField('total cost', validators = [DataRequired()])
    submit = SubmitField('submit')


class Order_Form(flask_wtf.FlaskForm):
    order_date = DateField('order date', validators = [DataRequired()])

    retail_name = StringField('retailer outlet', 
            validators =[DataRequired(), Length(1, 64)])

    retail_location = StringField('retailer location address',
            validators =[DataRequired(), Length(1, 64)])

    retail_email_address = StringField("retailer's email address", 
            validators = [DataRequired(), Length(1, 128), Email()])

    retail_phone_no = StringField("retailer's phone number", 
            validators = [DataRequired(), Length(1, 16)])

    submit = SubmitField('submit')

app/profiles/__init__.py
from flask import Blueprint, current_app
profiles = Blueprint('profiles', __name__)
from . import views, errors
from ..models import Permission 

@profiles.app_context_processor
def global_variables():
    return dict(app_name = current_app.config['ORGANISATION_NAME'], 
            Permission = Permission)

app/profiles/views.py
import flask, flask_login, calendar
from sqlalchemy import func, and_
from datetime import datetime, date
from . import profiles
from .. import db
from .forms import Order_Form, Service_Form, Add_Order_Form
from ..decorators import permission_required, admin_required
from ..models import (member, small_scale_farmer, order, trip, vehicle, driver, 
        vehicle_make, service, Permission, role, user, loader, loader_assignment)


@profiles.route('/user/view_trips/<int:user_id>', methods = ['GET', 'POST'])
@flask_login.login_required
@permission_required(Permission.TRIPS)
def user_view_trips(user_id):
    response = flask.make_response(flask.redirect(
        flask.url_for('profiles.user_page', user_id = user_id)
        )
    )
    response.set_cookie('user_tab_var', '0', max_age = 60*60)
    return response


@profiles.route('/user/registrations/<int:user_id>', methods = ['GET', 'POST'])
@flask_login.login_required
@permission_required(Permission.REGISTRATION)
def user_registrations(user_id):
    response = flask.make_response(flask.redirect(
        flask.url_for('profiles.user_page', user_id = user_id)
        )
    )
    response.set_cookie('user_tab_var', '1', max_age = 60*60)
    return response


@profiles.route('/user/finance/<int:user_id>', methods = ['GET', 'POST'])
@flask_login.login_required
@permission_required(Permission.FINANCE)
def user_finance(user_id):
    response = flask.make_response(flask.redirect(
        flask.url_for('profiles.user_page', user_id = user_id)
        )
    )
    response.set_cookie('user_tab_var', '2', max_age = 60*60)

    return response


@profiles.route('/user/services/<int:user_id>', methods = ['GET', 'POST'])
@flask_login.login_required
@permission_required(Permission.SERVICES)
def user_services(user_id):
    response = flask.make_response(flask.redirect(
        flask.url_for('profiles.user_page', user_id = user_id)
        )
    )
    response.set_cookie('user_tab_var', '3', max_age = 60*60)
    return response


@profiles.route('/user/summary/<int:user_id>', methods = ['GET', 'POST'])
@flask_login.login_required
@permission_required(Permission.SUMMARY)
def user_summary(user_id):
    response = flask.make_response(flask.redirect(
        flask.url_for('profiles.user_page', user_id = user_id)
        )
    )
    response.set_cookie('user_tab_var', '4', max_age = 60*60)
    return response


@profiles.route('/user/graphs/<int:user_id>', methods = ['GET', 'POST'])
@flask_login.login_required
@permission_required(Permission.GRAPHS)
def user_graphs(user_id):
    response = flask.make_response(flask.redirect(
        flask.url_for('profiles.user_page', user_id = user_id)
        )
    )
    response.set_cookie('user_tab_var', '5', max_age = 60*60)

    return response


@profiles.route('/user/offenders/<int:user_id>', methods = ['GET', 'POST'])
@flask_login.login_required
@permission_required(Permission.OFFENDERS)
def user_offenders(user_id):
    response = flask.make_response(flask.redirect(
        flask.url_for('profiles.user_page', user_id = user_id)
        )
    )
    response.set_cookie('user_tab_var', '6', max_age = 60*60)

    return response


@profiles.route('/user_page/<int:user_id>',methods = ['GET', 'POST'])
@flask_login.login_required
def user_page(user_id):
    current_user = user.query.filter(user.id == user_id).first()
    user_role = role.query.filter(
            role.role_id == current_user.role_id).first()
    
    user_tab_variable = 5
    if flask.request.cookies.get('user_tab_var') is not None:
        user_tab_variable = int(flask.request.cookies.get('user_tab_var'))

    #view trips
    if user_tab_variable == 0:

        future_trips = trip.query.filter(trip.trip_date > datetime.utcnow())\
                .join(vehicle, vehicle.vehicle_id == trip.vehicle_id)\
                .join(driver, driver.driver_id == trip.driver_id)\
                .join(vehicle_make, vehicle_make.make_id == vehicle.make_id)\
                .add_columns(
                        trip.trip_id,
                        trip.trip_date,
                        vehicle.plate_no,
                        vehicle_make.make_type,
                        driver.driver_id,
                        driver.first_name,
                        driver.middle_name,
                        driver.last_name,
                        driver.phone_no,
                        trip.distance,
                        vehicle_make.cost_per_km,
                        vehicle_make.no_of_loaders,
                        vehicle_make.loader_payment,
                        vehicle_make.driver_payment
                        ).order_by(trip.trip_date.desc()).all()
        
        past_trips = trip.query.filter(trip.trip_date < datetime.utcnow())\
                .join(vehicle, vehicle.vehicle_id == trip.vehicle_id)\
                .join(driver, driver.driver_id == trip.driver_id)\
                .join(vehicle_make, vehicle_make.make_id == vehicle.make_id)\
                .add_columns(
                        trip.trip_id,
                        trip.trip_date,
                        vehicle.plate_no,
                        vehicle_make.make_type,
                        driver.driver_id,
                        driver.first_name,
                        driver.middle_name,
                        driver.last_name,
                        driver.phone_no,
                        trip.distance,
                        vehicle_make.cost_per_km,
                        vehicle_make.no_of_loaders,
                        vehicle_make.loader_payment,
                        vehicle_make.driver_payment
                        ).order_by(trip.trip_date.desc()).all()


        return flask.render_template('profiles/user_page.html',
                user_tab_variable = user_tab_variable, future_trips = future_trips, 
                past_trips = past_trips, user_role = user_role.name)

    #user registrations
    elif user_tab_variable == 1:
        return flask.render_template('profiles/user_page.html',
            user_tab_variable = user_tab_variable, user_role = role.name)

    elif user_tab_variable == 2:
        return flask.render_template('profiles/user_page.html',
            user_tab_variable = user_tab_variable, user_role = role.name)

    elif user_tab_variable == 3:

        form = Service_Form()

        vehicles = [((item.vehicle_id), (item.plate_no)) \
                for item in vehicle.query.order_by(vehicle.plate_no.desc()).all()]

        form.vehicle_id.choices = vehicles

        if flask.request.method == 'POST' and form.validate_on_submit():
            s_service = service(
                    vehicle_id = form.vehicle_id.data,
                    description = form.description.data,
                    cost = form.cost.data              
                    )
            try:
                db.session.add(s_service)
                db.session.commit()
                
                flask.flash('Service details saved successfully.')
                return flask.redirect(flask.url_for('profiles.user_services', 
                    user_id = user_id))
                
            except IntegrityError:
                db.session.rollback()
                flask.flash('An error occurred while saving the details of the \
                        service. Please try again.')

            except:
                flask.flash('An error occurred while saving the details of the \
                        service. Please try again.')


        services = service.query\
                .join(vehicle, vehicle.vehicle_id == service.vehicle_id)\
                .join(vehicle_make, vehicle_make.make_id == vehicle.make_id)\
                .add_columns(
                        service.service_id,
                        service.date,
                        service.cost,
                        service.description,
                        vehicle.plate_no,
                        vehicle_make.make_type
                        ).order_by(service.date.desc()).all()

        return flask.render_template('profiles/user_page.html',
            user_tab_variable = user_tab_variable, services = services, form = form,
            user_role = user_role.name)

    elif user_tab_variable == 4:
        #trip_count = db.session.query(func.count().label('no_of_trips'),
        #        #extract('year', trip.trip_date),
        #        #extract())
        monthly_data = {}

        months = {1 : 'January', 2 : 'February', 3 : 'March', 4 : 'April', 
                5 : 'May', 6 : 'June', 7 : 'July', 8 : 'August', 9 : 'September', 
                10 : 'October', 11 : 'November',12 : 'December'}

        today = datetime.now()
        year = today.strftime('%Y')
        month = today.strftime('%-m')
        number_of_days_in_current_month = calendar.monthrange(int(year), 
                int(month))[1]
        start_date = date(int(year), int(month), 1)
        end_date = date(int(year), int(month), number_of_days_in_current_month)

        daily_data = db.session.query(trip).filter(and_(
            trip.trip_date >= start_date, trip.trip_date <= end_date)).all()

        return flask.render_template('profiles/user_page.html',
            user_tab_variable = user_tab_variable, monthly_data = monthly_data, 
            daily_data = daily_data, user_role = user_role.name)

    elif user_tab_variable == 5:
        return flask.render_template('profiles/user_page.html', 
            user_tab_variable = user_tab_variable, user_role = user_role.name)

    elif user_tab_variable == 6:
        return flask.render_template('profiles/user_page.html',
            user_tab_variable = user_tab_variable, user_role = user_role.name)


    return flask.render_template('profiles/user_page.html',
            user_tab_variable = user_tab_variable, user_role = user_role.name)


@profiles.route('/member/make_order/<int:member_id>', methods = ['GET', 'POST'])
def make_order(member_id):

app/templates/profiles/user_page.html
{% extends "base.html" %}

{% block title %}
    {{super()}}
    {{current_user.first_name}} {{current_user.last_name}} - {{user_role}}
{% endblock title %}

{% block page_content %}
    <div class = "profile-header">
            <h2>
		    {{current_user.first_name}} {{current_user.last_name}}
            </h2>
	    <caption>
		    <h3>{{user_role | title}}</h3>
	    </caption>
    </div>
    
    <div class = "container">
        {% if current_user.gender == 'female' %}
            <img class = "img-rounded profile-thumbnail" size = '256' src = "{{url_for('static', filename = 'profiles/female-avatar.png')}}">
        {% else %}
            <img class = "img-rounded profile-thumbnail" size = '256' src = "{{url_for('static', filename = 'profiles/male-avatar.png')}}">
        {% endif %}
    </div>
    
    <div class = "container">
        <table class = "table table-responsive table-hover table-striped">
            <caption><h3>Personal Information</h3></caption>
            <tbody>
                <tr>
		    <td>user ID</td>
		    <td>{{current_user.id}}</td>
                </tr>
                <tr>
                    <td>name</td>
		    <td>{{current_user.first_name}} {{current_user.last_name}}</td>
                </tr>
                <tr>
                    <td>gender</td>
                    <td>{{current_user.gender}}</td>
                </tr>
                <tr>
                    <td>age</td>
                    <td>{{ moment(current_user.date_of_birth).fromNow()}}</td>
                </tr>
                <tr>
                    <td>residence</td>
                    <td>{{current_user.residential_address}}</td>
                </tr>
                <tr>
		    <td>phone number</td>
                    <td>{{current_user.phone_no}}</td>            
                <tr>
                    <td>email</td>
                    <td>{{current_user.email_address}}</td>
                </tr>
            </tbody>
        </table>            
    </div>
        
    <div class = "container">
        <a class = 'btn btn-primary '>
           <span class="glyphicon glyphicon-pencil"> </span> Edit Profile
        </a>
    </div>
    <hr>
    <div class = "post-tabs">
	<ul class = "nav nav-tabs">
		<li class = "active">
			<a href = "{{url_for('profiles.user_view_trips', user_id = current_user.id)}}">
				trips
			</a>
		</li>
		<li>
			<a href = "{{url_for('profiles.user_registrations', user_id = current_user.id)}}">
				registration
			</a>
		</li>
		<li>
			<a href = "{{url_for('profiles.user_finance', user_id = current_user.id)}}">
				finance
			</a>
		</li>
		<li>
                        <a href = "{{url_for('profiles.user_services', user_id = current_user.id)}}">
                                services
                        </a>
                </li>
		<li>
			<a href = "{{url_for('profiles.user_summary', user_id = current_user.id)}}" >
				summary
			</a>
		</li>
		<li>
			<a href = "{{url_for('profiles.user_graphs', user_id = current_user.id)}}">
				graphs
			</a>
		</li>
	</ul>
    </div>
    <div class = "container">
    {% if user_tab_variable == 0 %}
    <div>
	    <h3>
		    <a href = "{{url_for('register.register_trip', user_id = current_user.id)}}">
			    click here to organize a trip
		    </a>
	    </h3>
    </div>
	    <table class = "table table-responsive table-hover table-striped">
		    <caption>
			    <h3>list of delivery trips</h3>
		    </caption>
		    <thead class = "thead-dark">
			    <tr>
				    <th>trip ID</th>
				    <th>date</th>
				    <th>vehicle</th>
				    <th>type</th>
				    <th>driver</th>
				    <th>phone number</th>
				    <th>distance</th>
				    <th>cost (Ksh)</th>
			    </tr>
		    </thead>
		    <tbody>
			    {% for trip in future_trips %}
			    {% set total_cost = ((trip.distance * trip.cost_per_km) + (trip.no_of_loaders * trip.loader_payment) + trip.driver_payment) %}
			    <tr>
				    <td>
					    <a href = "{{url_for('profiles.view_trip_details', trip_id = trip.trip_id)}}">
						    {{trip.trip_id}}
					    </a>
				    </td>
				    <td>{{trip.trip_date}}</td>
				    <td>{{trip.plate_no}}</td>
				    <td>{{trip.make_type}}</td>
				    <td>{{trip.first_name}} {{trip.middle_name}} {{trip.last_name}}</td>
				    <td>{{trip.phone_no}}</td>
				    <td>{{trip.distance}}</td>
				    <td>{{total_cost}}</td>
			    </tr>
			    {% endfor %}
		    </tbody>
	    </table>
	    <table class = "table table-responsive table-hover table-striped">
                    <caption>
                            <h3>list of past trips</h3>                                             </caption>                                                                          <thead class = "thead-dark">                                                                <tr>
                                    <th>trip ID</th>                                                                    <th>date</th>
                                    <th>vehicle</th>
                                    <th>type</th>                                                                       <th>driver</th>                                                                     <th>phone number</th>
                                    <th>distance</th>
				    <th>cost (Ksh)</th>                                                         </tr>                                                                       </thead>
                    <tbody>                                                                                     {% for trip in past_trips %}
			    {% set total_cost = ((trip.distance * trip.cost_per_km) + (trip.no_of_loaders * trip.loader_payment) + trip.driver_payment) %}                                          	<tr>
				    <td>
					    <a href = "{{url_for('profiles.view_trip_details', trip_id = trip.trip_id)}}">
						    {{trip.trip_id}}
					    </a>
				    </td>
                                    <td>{{trip.trip_date}}</td>
				    <td>{{trip.plate_no}}</td>                                                          <td>{{trip.make_type}}</td>                                                         <td>
					    <a href = "{{url_for('profiles.view_driver_profile', driver_id = trip.driver_id)}}">
						    {{trip.first_name}} {{trip.middle_name}} {{trip.last_name}}
					    </a>
				    </td>                                                                                                    <td>{{trip.phone_no}}</td>                                                          <td>{{trip.distance}}</td>                                                          <td>{{total_cost}}</td>
			    </tr>
			    {% endfor %}
		    </tbody>
            </table>

    {% elif user_tab_variable == 1 %}
    <div class = "container-fluid">
    <div class = "row">
    <div class = "col-md-6">
	    <h4 class = "text-uppercase font-weight-bold">Register</h4>

	    <p><a href = "{{url_for('register.register_vehicle')}}">vehicle</a></p>
	    <p><a href = "{{url_for('register.register_vehicle_make')}}">
		    vehicle make
	    </a></p>
	    <p><a href = "{{url_for('register.register_driver')}}">driver</a></p>
	    <p><a href = "{{url_for('register.register_loader')}}">loader</a></p>
	    <p><a href = "{{url_for('register.register_offence')}}">offense</a></p>
	    <p><a href = "{{url_for('register.register_good')}}">commodity</a></p>
    </div>
    <div class = "col-md-6">
	    <h4 class = "text-uppercase font-weight-bold">view records</h4>
	    <p><a href = "{{url_for('records.list_of_members')}}">members</a></p>

	    <p>
	    <a href = "{{url_for('records.list_of_small_scale_farmers')}}">
		    small scale farmers
	    </a>
	    </p>

	    <p><a href = "{{url_for('records.list_of_vehicles')}}">vehicles</a></p>
	    <p><a href = "{{url_for('records.list_of_vehicle_makes')}}">vehicle makes</a></p>
	    <p><a href = "{{url_for('records.list_of_drivers')}}">drivers</a></p>
	    <p><a href = "{{url_for('records.list_of_loaders')}}">loaders</a></p>
	    <p><a href = "{{url_for('records.list_of_goods')}}">commodities</a></p>
	    <p><a href = "{{url_for('records.list_of_offences')}}">offenses</a></p>
    </div>
    </div>
    </div>

    {% elif user_tab_variable == 2 %}

    {% elif user_tab_variable == 3 %}

    <div class = "container">
	    <h3 class = "text-muted">
		    enter service details
	    </h3>
	    {{ wtf.quick_form(form) }}
    </div>

    <table class = "table table-responsive table-hover table-triped">
	    <caption>
		    <h3>
			    records of services
		    </h3>
	    </caption>
	    <thead class = "thead-dark">
		    <tr>
			    <th>service ID</th>
			    <th>date</th>
			    <th>vehicle</th>
			    <th>type</th>
			    <th>description</th>
			    <th>cost</th>
		    </tr>
	    </thead>
	    <tbody>
		    {% for service in services %}
		    <tr>
			    <td>{{service.service_id}}</td>
			    <td>{{service.date}}</td>
			    <td>{{service.plate_no}}</td>
			    <td>{{service.make_type}}</td>
			    <td>{{service.description}}</td>
			    <td>{{service.cost}}</td>
		    </tr>
		    {% endfor %}
	    </tbody>
    </table>

    {% elif user_tab_variable == 4 %}
    <table class = "table table-responsive table-hover table-striped">
	    <caption>
		    <h3>
			    An account of monthly wages
		    </h3>
	    </caption>
	    <thead class = "thead-dark">
		    <tr>
			    <th>month</th>
			    <th>number of trips</th>
			    <th>cost of services</th>
			    <th>labor cost</th>
			    <th>net tax</th>
			    <th>miscellaneous</th>
			    <th>total</th>
		    </tr>
	    </thead>
	    <tbody>
		    {% for item in monthly_data %}
		    <tr>
			    <td>{{item.trip_date}}</td>
		    </tr>
		    {% endfor %}
	    </tbody>
    </table>
    <table class = "table table-responsive table-hover table-striped">
	    <caption>
		    <h3>
			    An account of daily wages
		    </h3>
	    </caption>
	    <thead class = "thead-dark">
		<tr>
		    <th>date</th>
		    <th>number of trips</th>
		    <th>cost of services</th>
		    <th>labor cost</th>
		    <th>net tax</h>
		    <th>miscellaneous</th>
		    <th>total</th>
		</tr>
	    </thead>
	    <tbody>
		{% for item in daily_data %}
		<tr>
			<td>{{item.trip_date}}</td>
		</tr>
		{% endfor %}
	    </tbody>
    </table>

    {% elif user_tab_variable == 5 %}

    {% endif %}
    </div>
{% endblock page_content %}

app/templates/profiles/view_loader_profile.html
{% extends "base.html" %}

{% block title %}
    {{super()}}
    {{loader.first_name}} {{loader.middle_name}} {{loader.last_name}} - {{loader.loader_id}}
{% endblock title %}

{% block page_content %}
    <div class = "profile-header">
            <h2>
		{{loader.first_name}} {{loader.middle_name}} {{loader.last_name}}
            </h2>
	    <caption>
		    <h3>loader</h3>
	    </caption>
    </div>
    
    <div class = "container">
        {% if loader.gender == 'female' %}
            <img class = "img-rounded profile-thumbnail" size = '256' src = "{{url_for('static', filename = 'profiles/female-avatar.png')}}">
        {% else %}
            <img class = "img-rounded profile-thumbnail" size = '256' src = "{{url_for('static', filename = 'profiles/male-avatar.png')}}">
        {% endif %}
    </div>
    
    <div class = "container">
        <table class = "table table-responsive table-hover table-striped">
            <caption><h3>Personal Information</h3></caption>
            <tbody>
                <tr>
		    <td>loader ID</td>
		    <td>{{loader.loader_id}}</td>
                </tr>
                <tr>
                    <td>name</td>
		    <td>{{loader.first_name}} {{loader.middle_name}} {{loader.last_name}}</td>
                </tr>
                <tr>
                    <td>gender</td>
                    <td>{{loader.gender}}</td>
                </tr>
                <tr>
                    <td>age</td>
                    <td>{{ moment(loader.date_of_birth).fromNow()}}</td>
                </tr>
                <tr>
                    <td>residence</td>
                    <td>{{loader.residential_address}}</td>
                </tr>
                <tr>
		    <td>phone number</td>
                    <td>{{loader.phone_no}}</td>            
                <tr>
                    <td>email</td>
                    <td>{{loader.email_address}}</td>
                </tr>
            </tbody>
        </table>            
    </div>
        
    <div class = "container">
        <a class = 'btn btn-primary '>
           <span class="glyphicon glyphicon-pencil"> </span> Edit Profile
        </a>
    </div>
    <hr>
    <div class = "post-tabs">
	<ul class = "nav nav-tabs">
		<li class = "active">
			<a href = "{{url_for('profiles.loader_assigned_trips', loader_id = loader.loader_id)}}">
				assigned trips
			</a>
		</li>
		<li>
			<a href = "{{url_for('profiles.loader_financial_records', loader_id = loader.loader_id)}}">
				financial records
			</a>
		</li>
	</ul>
    </div>
    {% if loader_tab_variable == 0 %}
    <div class = "container">
	<table class = "table table-responsive table-hover table-striped">
		<caption>
			<h3>list of assigned trips</h3>
		</caption>
		<thead class = "thead-dark">
			<tr>
				<th>trip id</th>
				<th>trip date</th>
				<th>vehicle</th>
				<th>type</th>
				<th>driver</th>
				<th>phone number</th>
				<th>distance</th>
			</tr>
		</thead>
		<tbody>
			{% for trip in future_trips %}
			<tr>
				<td>{{trip.trip_id}}</td>
				<td>{{trip.trip_date}}</td>
				<td>{{trip.plate_no}}</td>
				<td>{{trip.make_type}}</td>
				<td>
					{{trip.first_name}} {{trip.middle_name}} {{trip.last_name}}
				</td>
				<td>{{trip.phone_no}}</td>
				<td>{{trip.distance}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
    </div>
    {% elif loader_tab_variable == 1 %}
    <div class = "container">
    </div>
    {% elif loader_tab_variable == 2 %}
    <div class = "container">
    </div>
    {% endif %}
{% endblock page_content %}

app/templates/profiles/view_member_profile.html
{% extends "base.html" %}
{% block title %}
    {{super()}}
    view member profile
{% endblock title%}

{% block page_content %}
<div class="page-header">
	<h1>{{member.name}}</h1>
</div>

<div class = "container">
	<img src = "{{url_for('static', filename = 'move/Farmer_5.jpeg')}}" class = "img-rounded" style = "width : 100%; height : auto;">
</div>


{% if member.status == "group" %}
<div class = "container">
	<table class = "table table-responsive table-hover table-striped">
		<caption>
			<h3>members</h3>
		</caption>
		<thead class = "thead-dark">
			<tr>
				<th>reg. ID</th>
				<th>name</th>
				<th>email address</th>
				<th>phone number</th>

			</tr>
		</thead>
		<tbody>
			{% for farmer in farmers %}
			<tr>
				<td>{{farmer.farmer_id}}</td>
				<td>{{farmer.first_name}} {{farmer.middle_name}} {{farmer.last_name}}</td>
				<td>{{farmer.email_address}}</td>
				<td>{{farmer.phone_no}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<div class = "container">
		<p>
		Want to add a new member?
		<a class = 'btn btn-primary' href = "{{url_for('register.register_small_scale_farmer', member_id = member.member_id)}}">
			Click here to register
		</a>
		</p>
	</div>
</div>
{% endif %}

<div class = "container">
	<div class = "post-tabs">
		<ul class = "nav nav-tabs">
			<li>
				<a href = "{{url_for('profiles.make_order', member_id = member.member_id)}}">
					order now
				</a>
			</li>
			<li>
				<a href = "{{url_for('profiles.view_orders', member_id = member.member_id)}}">
					orders
				</a>
			</li>
			<li>
				<a href = "{{url_for('profiles.make_order', member_id = member.member_id)}}">
					deliveries
				</a>
			</li>
			<li>
				<a href = "{{url_for('profiles.make_order', member_id = member.member_id)}}">
					summary
				</a>
			</li>
			<li>
				<a href = "{{url_for('profiles.make_order', member_id = member.member_id)}}">
					financial records
				</a>
			</li>
		</ul>
	</div>
</div>

<div class = "container">

{% if tab_variable == 0 %}
<caption>
	<h3>want to make an order?</h3>
</caption>

{{wtf.quick_form(form)}}

{% elif tab_variable == 1 %}
<table class = "table table-responsive table-hover table-striped">
	<caption>
		<h3>orders made</h3>
	</caption>
	<thead class = 'thead-dark'>
		<tr>
			<th>order ID</th>
			<th>order date</th>
			<th>retail outlet</th>
			<th>location</th>
			<th>email address</th>
			<th>phone number</th>
		</tr>
	</thead>
	<tbody>
		{% for order in orders %}
		<tr>
			<td>{{order.order_id}}</td>
			<td>{{order.order_date}}</td>
			<td>{{order.retail_name}}</td>
			<td>{{order.retail_location}}</td>
			<td>{{order.retail_email}}</td>
			<td>{{order.retail_phone_no}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endif %}

{% if tab_variable == 2 %}                                                          {% endif %}

{% if tab_variable == 3 %}                                                          {% endif %}

{% if tab_variable == 4 %}                                                          {% endif %}

</div>
{% endblock page_content %}